# Generated by Django 2.0.2 on 2022-10-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeTimeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifeTime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LiquidInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('li_height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemType', models.IntegerField(default=0)),
                ('networkType', models.IntegerField(default=0)),
                ('runType', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ThickInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
