# Generated by Django 2.0.2 on 2022-10-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo01', '0002_auto_20221017_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarmInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness_warm', models.IntegerField()),
                ('height_warm', models.IntegerField()),
            ],
        ),
    ]
