# Generated by Django 2.0.2 on 2022-10-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo01', '0004_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
