# Generated by Django 4.1 on 2022-12-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo01', '0006_auto_20221019_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThickInfo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.IntegerField()),
                ('date', models.DateField(default='2022-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='ThickInfo3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.IntegerField()),
                ('date', models.DateField(default='2022-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='ThickInfo4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.IntegerField()),
                ('date', models.DateField(default='2022-01-01')),
            ],
        ),
    ]
