# Generated by Django 2.0.2 on 2023-01-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo01', '0007_thickinfo2_thickinfo3_thickinfo4'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastid_1', models.IntegerField()),
                ('lastid_2', models.IntegerField()),
                ('lastid_3', models.IntegerField()),
                ('lastid_4', models.IntegerField()),
            ],
        ),
    ]
