# Generated by Django 2.0.2 on 2023-03-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo01', '0009_auto_20230330_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thickinfo2',
            name='date',
            field=models.DateTimeField(default='2022-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='thickinfo3',
            name='date',
            field=models.DateTimeField(default='2022-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='thickinfo4',
            name='date',
            field=models.DateTimeField(default='2022-01-01 00:00:00'),
        ),
    ]
