# Generated by Django 2.0.2 on 2023-03-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo01', '0010_auto_20230330_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128)),
            ],
        ),
    ]
